### ISSUE TITLE
Crashes as soon as launched

### ISSUE THREAD

**Issue by agektmr** [maxlgu/BobBucksAndroidPaymentApp#1] opened 2021-12-10 01:09 UTC
The app crashes as soon as it's launched.
This may be because I'm using old-ish build of Android 12 on Pixel 3 but can you check?

**Comment by liquangumax** [comment] 2021-12-10 03:38
It crashes on my side as well. I've just fixed the crash. It was caused by a mismatch in activity name. Nothing needs to be changed on bobbucks.dev.

Thanks for your report!

**Comment by maxlgu** [comment] 2021-12-10 03:40
Fixed by https://github.com/maxlgu/BobBucksAndroidPaymentApp/commit/817fb1980c297e8e996849d72df7814d02d5a45b

**Closed as completed** 2021-12-10 03:39 UTC
